# This workflow runs continuous CI across different versions of ruby on all branches and pull requests to develop.

name: CI
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  tests:
    name: Ruby ${{ matrix.ruby }}
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - ruby-head
          - jruby
        mongodb-version:
          - 4.4
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: bundle exec rspec spec
 
